# Generated by Django 5.2.14 on 2026-05-24 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_index', models.IntegerField(blank=True, help_text='Row index in original file', null=True)),
                ('date', models.DateField()),
                ('scope', models.CharField(choices=[('Scope 1', 'Scope 1 - Direct Emissions'), ('Scope 2', 'Scope 2 - Indirect Emissions (Electricity)'), ('Scope 3', 'Scope 3 - Indirect Emissions (Value Chain)')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('original_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('original_unit', models.CharField(max_length=20)),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=20)),
                ('co2e_kg', models.DecimalField(decimal_places=4, help_text='Calculated carbon in kilograms of CO2e', max_digits=18)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved & Locked'), ('rejected', 'Rejected'), ('suspicious', 'Suspicious / Flagged')], default='pending', max_length=20)),
                ('suspicious_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_ingestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ingestion.rawingestion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accounts.tenant')),
            ],
        ),
    ]
